/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * VariantExplain API
 * API for VariantExplain application
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface HealthResponse {
  status: string;
}

export type RootGet200 = {[key: string]: string};

/**
 * Root endpoint that returns a welcome message.
 * @summary Root
 */
export const rootGet = <TData = AxiosResponse<RootGet200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:8000/`,options
    );
  }

/**
 * Health check endpoint for monitoring.
 * @summary Health Check
 */
export const healthCheckHealthGet = <TData = AxiosResponse<HealthResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:8000/health`,options
    );
  }

export type RootGetResult = AxiosResponse<RootGet200>
export type HealthCheckHealthGetResult = AxiosResponse<HealthResponse>
